-- Seed Superadmin User for DOIEHub
-- Admin Ikhsane with password "Sidoarjo1!"
-- This user cannot be deleted and is system-managed

-- Get the SuperAdmin role ID
DO $$
DECLARE
  superadmin_role_id UUID;
  password_hash VARCHAR(255);
BEGIN
  -- Get SuperAdmin role ID
  SELECT id INTO superadmin_role_id FROM roles WHERE name = 'SuperAdmin';
  
  -- Hash for "Sidoarjo1!" using bcrypt (this is a placeholder - will be generated by Node.js)
  -- For now, we'll use a bcrypt hash. In production, this should be created via Node.js
  password_hash := '$2b$10$Z8Q5K8q8K8q8K8q8K8q8K.8q8K8q8K8q8K8q8K8q8K8q8K8q8K8q8';
  
  -- Insert Ikhsane as SuperAdmin if doesn't exist
  INSERT INTO users (id, email, password_hash, name, role_id, amount_balance, is_active)
  VALUES (
    '00000000-0000-0000-0000-000000000001'::UUID,
    'ikhsane@doiehub.local',
    password_hash,
    'Ikhsane',
    superadmin_role_id,
    1000,
    TRUE
  )
  ON CONFLICT (email) DO NOTHING;
END $$;
